### ISSUE TITLE
An option to add/edit JSON schemas

### ISSUE THREAD

**Issue by x-2mas** [Blockception/VSCode-Bedrock-Development-Extension#429]
An option to edit the JSON validation files used by the diagnoser would be really nice for those of us who work with more experimental, non-standard features. Currently, the projects I'm working on have so many falsely-flagged errors, it kinda renders diagnostics useless. Some examples:

- The health component can have a 'min' field (used to make entities immortal) but the schema only supports 'max' and 'value'.
- Animation files exported by Blockbench get flagged for having 'bones' in the wrong place, but works perfectly fine in-game.
- Some components like saturation, knockback, etc can have a 'max' field but this is flagged as invalid.

In fact, it's quite ironic how so many files in the Vanilla Packs are also flagged as having errors. I understand this is not your fault as you're probably just using schema files provided by Mojang, but it would be really nice if we could suppress those errors by editing the schemas ourselves. Thanks.

**Comment by DaanV2** [comment]
The schemas that are used are handwritten and maintained by us.
However, we don't support anything experimental since it is unknown if it will be scrapped or not, as well as the high amount of extra time needed to support experimental options. We also only support things as how they are documented, or found in the vanilla packs. The min field for example is one of them.

>Animation files exported by Blockbench get flagged for having 'bones' in the wrong place, but works perfectly fine in-game.

I haven't seen this happen, so if you have an example great 😄 

>In fact, it's quite ironic how so many files in the Vanilla Packs are also flagged as having errors

You be supprised how many of them are in fact valid errors they have made, or not adhering to the set conventions.

As for the feature request, I cannot do anything dynamically myself on what you want.
But you can take the schemas from:
https://github.com/Blockception/Minecraft-bedrock-json-schemas
and modify as you want

**Comment by x-2mas** [comment]
Great, thanks! Is it possible to load those modified schemas into the extension's diagnoser?

**Comment by x-2mas** [comment]
wait nvm.. I just realized we could use them manually
